require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'db/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
