default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: '5432'
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: kutima_development

test:
  <<: *default
  database: kutima_test

production:
  <<: *default
  database: kutima_production
  username: kutima
  password: <%= ENV['KUTIMA_DATABASE_PASSWORD'] %>
