common: &default_settings
license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  distributed_tracing:
    enabled: true
  log_level: info

development:
  <<: *default_settings
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: habit-tracker-rails-staging

production:
  <<: *default_settings
  app_name: habit-tracker-rails-prod
